import { NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs/promises';

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        // Use all_stocks.json generated by script
        // Use all_stocks.json from db-data branch (GH Raw)
        const branch = 'db-data';
        const url = `https://raw.githubusercontent.com/hoonnamkoong/stockbot/${branch}/data/all_stocks.json`;

        let stocks: Array<{ code: string, name: string }> = [];
        try {
            const res = await fetch(url, { cache: 'no-store' });
            if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
            const rawData = await res.json();

            // Transform complex scraper data to simple {code, name} format
            if (Array.isArray(rawData)) {
                stocks = rawData.map((item: any) => ({
                    code: item.code,
                    name: item.name
                }));
            }
            console.log(`[Stocks] Loaded ${stocks.length} items from ${branch}`);
        } catch (e) {
            console.error("Failed to fetch all_stocks.json from GitHub:", e);
            // Fallback hardcoded list
            stocks = [
                { code: "005930", name: "삼성전자" },
                { code: "000660", name: "SK하이닉스" },
                { code: "035420", name: "NAVER" },
                { code: "035720", name: "카카오" }
            ];
        }

        return NextResponse.json({ stocks });
    } catch (error) {
        return NextResponse.json({ error: 'Failed to load stock list' }, { status: 500 });
    }
}
