import { NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs/promises';

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        // Use all_stocks.json generated by script
        const jsonPath = path.join(process.cwd(), 'data', 'all_stocks.json');

        let stocks = [];
        try {
            const fileContent = await fs.readFile(jsonPath, 'utf-8');
            stocks = JSON.parse(fileContent);
        } catch (e) {
            console.error("Failed to read all_stocks.json", e);
            // Fallback hardcoded list if file missing
            stocks = [
                { code: "005930", name: "삼성전자" },
                { code: "000660", name: "SK하이닉스" },
                { code: "035420", name: "NAVER" },
                { code: "035720", name: "카카오" }
            ];
        }

        return NextResponse.json({ stocks });
    } catch (error) {
        return NextResponse.json({ error: 'Failed to load stock list' }, { status: 500 });
    }
}
